### ISSUE TITLE
how to to display plane Ax + By + Cz + D = 0

### ISSUE THREAD

**Issue by aidenyao** [PickNikRobotics/rviz_visual_tools#118]

**Comment by matthaeusheer** [comment]
Support this question, need to solve the exact same problem.  
I have model coefficients (```pcl::ModelCoefficients::Ptr coefficients(new pcl::ModelCoefficients);```) which I would like to use to publish planes using some sort of translation and rotation.

**Comment by AndyZe** [comment]
I started a [branch](https://github.com/PickNikRobotics/rviz_visual_tools/tree/display_plane) for this feature but rotation is not correct yet. [This question](https://answers.ros.org/question/266391/quaternion-to-rotate-rigid-frame/) on answers.ros.org has a solution for the rotation. If you like, you could implement that solution around line 981 of rviz_visual_tools.cpp

**Comment by AndyZe** [comment]
@aidenyao @matthaeusheer  Can you please test out PR #119 and let me know if it works for you.

**Comment by matthaeusheer** [comment]
Hey, thanks for the work. I will checkout it out tomorrow!

**Comment by AndyZe** [comment]
#119
