### ISSUE TITLE
trigger() blocks forever - bug?

### ISSUE THREAD

**Issue by CodeFinder2** [PickNikRobotics/rviz_visual_tools#146]
Hi,

I am facing the problem that
```cpp
    ROS_ERROR("FOO");
    visual_tools->trigger();
    ROS_ERROR("BAR");
```
does not return. Even when Rviz connects, nothing will happen. I don't know if this is related to my issue but note that neither `visual_tools->loadMarkerPub(false, true);` nor `visual_tools->loadMarkerPub(true, true);` is working. (I am requiring latched topics.)

Once I comment this block:
```cpp
  // Check if connected to a subscriber
  if (!pub_rviz_markers_waited_ && !pub_rviz_markers_connected_)
  {
    ROS_DEBUG_STREAM_NAMED(LOGNAME, "Waiting for subscribers before publishing markers...");
    waitForSubscriber(pub_rviz_markers_);

    // Only wait for the publisher once, after that just ignore the lack of connection
    pub_rviz_markers_waited_ = true;
  }
```
in the [implementation of `RvizVisualTools::publishMarkers()`](https://github.com/PickNikRobotics/rviz_visual_tools/blob/master/src/rviz_visual_tools.cpp#L891) (invoked by `trigger()`), it is working fine.

Is this a bug? IMHO, there should be the possibility to skip the `waitForSubscriber()`.

**Comment by CodeFinder2** [comment]
Okay, nevermind: it is related to the `ros::spinOnce()` in `RvizVisualTools::waitForSubscriber()`. I have previously locked a mutex and if `spinOnce()` invoked a callback (locking the mutex again), it deadlocks.

So, would it be possible to skip `waitForSubscriber()`? Probably adding an additonal parameter?

**Comment by mfocchi** [comment]
Me and all my research group have the exact same issue. Is it going to be fixed? In which version?
