### ISSUE TITLE
rviz crashes when using publishMesh with shape_msgs::Mesh message

### ISSUE THREAD

**Issue by yuzhou42** [PickNikRobotics/rviz_visual_tools#175]
My rviz crashed after subscribing to my shape_msgs for a few seconds. It works fine with other topics. The mesh msg has  4286436 vertices and 1428812 faces and published with 1hz frequency. The output on the terminal is `[1]    13512 killed     rviz`.

**Comment by JafarAbdi** [comment]
Hi @yuzhou42,

Can you share the backtrace when Rviz crashes  .?

**Comment by yuzhou42** [comment]
Hi Jafar, thank you for your reply. I think I found the reason. I should have set the id to any number other than 0 when publishing mesh, otherwise the memory is not enough which caused the crash I guess.  Thanks!
