### ISSUE TITLE
Typo in package.xml ("butracker" instead of "bugtracker")

### ISSUE THREAD

**Issue by pichlermarc** [PickNikRobotics/rviz_visual_tools#182]
Hi everyone!

There seems to be a typo in the `package.xml`-file where the URL type is set to `"butracker"` instead of `"bugtracker"`. 

https://github.com/PickNikRobotics/rviz_visual_tools/blob/240b6ecf0f05ff5c08d4382b18db8c47b091663d/package.xml#L12

It's just a small problem that does not affect much, however it does not verify against the [XSD of Package Format Version 2](http://download.ros.org/schema/package_format2.xsd).

**Comment by vatanaksoytezer** [comment]
Fixed by #187
