### ISSUE TITLE
Default constructor is not nodelet friendly

### ISSUE THREAD

**Issue by shaun-edwards** [PickNikRobotics/rviz_visual_tools#49]
The `rviz_visual_tools` constructor does not allow the node handle to be passed into the class, rather it initializes the node handle `nh_("~")` [here](https://github.com/davetcoleman/rviz_visual_tools/blob/kinetic-devel/src/rviz_visual_tools.cpp#L55).  When using nodelets, this results in topics being published under an anonymous namespace (which changes every time the nodelet is launched).

I believe the appropriate fix is to allow the node handle to be passed in on construction.  When using nodelets, the user should pass in `getNodeHandle()`.

**Comment by shaun-edwards** [comment]
I'm happy to submit a PR to address this, if indeed I am correct and it is an issue.

Would you accept a PR against `indigo`?

**Comment by davetcoleman** [comment]
I'd accept it to indigo. Make sure the new constructor has a default value for ``nh`` if the user does not specify. We'll then cherry-pick it to J/K

**Comment by davetcoleman** [comment]
Any progress on this or should this issue be closed?

**Comment by shaun-edwards** [comment]
I plan to get back to this in the new year, but no longer on indigo.  @geoffreychiou...do you want to have a look at this?

**Comment by geoffreychiou** [comment]
@shaun-edwards On kinetic?

**Comment by shaun-edwards** [comment]
Kinetic...it looks like this is the latest [LTS](http://wiki.ros.org/Distributions)

**Comment by VictorLamoine** [comment]
@davetcoleman you forgot to close this issue
