### ISSUE TITLE
3 ambiguous methods

### ISSUE THREAD

**Issue by JavaJeremy** [PickNikRobotics/rviz_visual_tools#73]
The 3 publishPath methods, starting at:
https://github.com/PickNikRobotics/rviz_visual_tools/blob/kinetic-devel/include/rviz_visual_tools/rviz_visual_tools.h#L662
have only one mandatory parameter, just like the ones before.
```
publishPath(const std::vector<geometry_msgs::Point>& path)
publishPath(const EigenSTL::vector_Vector3d& path)
publishPath(const EigenSTL::vector_Affine3d& path)
```

So if I call any of them with only the first parameter I get an error while compiling:
> error: call of overloaded ‘publishPath(std::vector<geometry_msgs::Point_<std::allocator<void> > >&)’ is ambiguous

Could you make the optional parameters mandatory for one set of methods to resolve this ambiguity?

@v4hn

**Comment by mcevoyandy** [comment]
@JavaJeremy could you make the pull request for this change? If so I'll review and merge, otherwise it might take me some time to get to it.  Thanks!
